apiVersion: v2
name: file-integrity-console-plugin
description: OpenShift console plugin for the Red Hat File Integrity Operator
type: application
version: 0.4.1
appVersion: "0.4.1"
keywords:
  - openshift
  - console-plugin
  - file-integrity
  - compliance
