apiVersion: v2
name: file-integrity-console-plugin
description: OpenShift console plugin for the Red Hat File Integrity Operator
type: application
version: 0.1.0-ocp4.16
appVersion: "0.1.0-ocp4.16"
keywords:
  - openshift
  - console-plugin
  - file-integrity
  - compliance
